export const plansList = {
    silver: {
        name: 'Silver',
        price: "$0.00",
        description: 'For most businesses that want to optimize web queries',
        UIDesign: true,
        webDevelopment: true,
        logoDesign: false,
        seoOptimization: false,
        wordPressIntegration: false,
        fiveWebsites: false,
        unlimitedUsers: false,
        bandwidth: false,
        mostPopular: false,
    },
    gold: {
        name: 'Gold',
        price: "$50.00",
        description: 'For most businesses that want to optimize web queries',
        UIDesign: true,
        webDevelopment: true,
        logoDesign: true,
        seoOptimization: true,
        wordPressIntegration: false,
        fiveWebsites: false,
        unlimitedUsers: false,
        bandwidth: false,
        mostPopular: true,
    },
    platinum: {
        name: 'Platinum',
        price: "$80.00",
        description: 'For most businesses that want to optimize web queries',
        UIDesign: true,
        webDevelopment: true,
        logoDesign: true,
        seoOptimization: true,
        wordPressIntegration: true,
        fiveWebsites: true,
        unlimitedUsers: true,
        bandwidth: true,
        mostPopular: false,
    }
}